apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot
  labels:
    app: spring12
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring12
  template:
    metadata:
      labels:
        app: spring12
    spec:
      containers:
      - name:  spring-boot
        image: rohanchau/spring-boot-docker.jar

        ports:
        - containerPort: 80
      