apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot
  labels:
    app: spring1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      labels:
        app: spring1
    spec:
      containers:
      - name:  spring-boot
        image: rohanchau/spring-boot-docker.jar

        ports:
        - containerPort: 80
      