apiVersion: apps/v1
kind: Deployment
metadata:
  name: console-java
  labels:
    app: java1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java1
  template:
    metadata:
      labels:
        app: java1
    spec:
      containers:
      - name:  console-java
        image: rohanchau/sampledocker
        ports:
        - containerPort: 80
      